language: node_js
sudo: required
addons:
  chrome: stable
  sonarcloud:
    organization: "lafeuille"
script:
  - "npm run lint"
  - "npm test -- --watch false --browsers ChromeHeadless --codeCoverage true"
  - "npm run build -- --prod"
  - sonar-scanner
before_deploy:
  - npm install -g firebase-tools
deploy:
  - provider: firebase
    skip_cleanup: true
    token: $FIREBASE_TOKEN
    project: lafeuille-ljcp
    on:
      branch: master
  - provider: firebase
    skip_cleanup: true
    token: $FIREBASE_TOKEN
    project: lafeuille-ljcp-staging
    on:
      branch: develop
