version: '2.1'

services:
  ljcp-ng:
    image: ljcp-ng
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 80:443
    ## set your startup file here
    command: [nginx-debug, '-g', 'daemon off;']
